### ISSUE TITLE
Could you please upgrade aspectJ dependency from 1.9.2 -> 1.9.19

### ISSUE THREAD

**Issue by Sanady** [reportportal/agent-java-junit5#112]
**Is your feature request related to a problem? Please describe.**
Hello, currently I am upgrading my tests to Java 17 (from Java 11), and I am facing issues with AspectJ. Could you please upgrade it?

**Describe the solution you'd like**
The solution is a potential fix for all people that are going to upgrade.

**Describe alternatives you've considered**
Currently, there is no alternative.

**Additional context**
None

**Comment by HardNorth** [comment]
@Sanady HI, thanks for pointing this out. Unfortunately I'm not free to update everything to the latest versions, since I need to keep it compatible with different devices, like Android. I'll try to test the latest version of AspectJ, but most likely it will be version 1.9.8.

**Comment by Sanady** [comment]
Thank you for fast reply, it would be nice to see upgrade to 1.9.8 either. Version 1.9.8. is supporting Java 17.

**Comment by HardNorth** [comment]
@Sanady Looks like even the latest version of AspectJ does not affect Android build, so I updated it.
