### ISSUE TITLE
Not Found link at README

### ISSUE THREAD

**Issue by ajax-kovtunov-o** [reportportal/agent-java-junit5#121]
The link from READMI is invalid cause the result is not found 
1. The link at README
https://github.com/reportportal/agent-java-junit5?tab=readme-ov-file#step-4---configuring-reportportal

![image](https://github.com/reportportal/agent-java-junit5/assets/123635332/501873f0-3e8a-4a5e-9e96-c60735259ef7)

2. The result of link
![image](https://github.com/reportportal/agent-java-junit5/assets/123635332/5b7e7f55-d1a4-4d70-b695-81d6b6f3e60b)

**Comment by HardNorth** [comment]
@ajax-kovtunov-o, Thank you! I'll try to fix it on the next week. Since I believe it needs to be rewritten a bit.

**Comment by HardNorth** [comment]
Fixed
