### ISSUE TITLE
Multimodule Gradle project generates multiple lunches

### ISSUE THREAD

**Issue by siwonpawel** [reportportal/agent-java-junit5#132]
**Describe the bug**
Include agent into multimodule gradle project is resulting in as many lunches created as modules in a project.

**Steps to Reproduce**
1. Create gradle project
2. Add two or more modules with some tests into the project
3. Create shared [build logic ](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html) that will include report portal agent and generate required resource files

```groovy
dependencies {
    testImplementation 'com.epam.reportportal:agent-java-junit5:5.3.2'
}

test {
    systemProperty 'junit.jupiter.extensions.autodetection.enabled', true
}

def reportPortal = tasks.register("reportPortal") {
    def serviceFilename = "org.junit.jupiter.api.extension.Extension"
    def serviceFileContent = "com.epam.reportportal.junit5.ReportPortalExtension"
    def reportPortalFilename = "reportportal.properties"

    def reportPortalFileContent = """
            rp.enable = true
            rp.endpoint = https://reportportal.prod.k8s.production.cdq-cloud-engine.com
            rp.uuid = XXXXXXXXXXXXX
            rp.launch = ${rootProject.name}
            rp.project = XXXXXXXXXXXXXXX
            """

    def resourcesDir = layout.buildDirectory.dir("generated/resources").get()
    if (!resourcesDir.asFile.exists()) {
        resourcesDir.asFile.mkdirs()
    }

    def metaInfDir = layout.buildDirectory.dir("generated/resources/META-INF/services").get()
    if (!metaInfDir.asFile.exists()) {
        metaInfDir.asFile.mkdirs()
    }

    def servicesFile = metaInfDir.file(serviceFilename)
    def reportPortalFile = resourcesDir.file(reportPortalFilename)

    outputs.files(servicesFile, reportPortalFile)

    doLast {
        servicesFile.asFile.text = serviceFileContent
        reportPortalFile.asFile.text = reportPortalFileContent

        project.logger.info("JUnit 5 services file created:", servicesFile.asFile.absolutePath)
        project.logger.info("ReportPortal file created:", reportPortalFile.asFile.absolutePath)
    }
}

tasks.processResources.dependsOn(reportPortal)

processResources {
    from(layout.buildDirectory.dir("generated/resources"))
}
```  

**Expected behavior**
Single lunch created for `./gradlew build`

**Actual behavior**
As many lunches created as many of the modules the project has.

**Dependency versions**
Include version info of the following libraries: client-java, agent-java-junit5

java 17
testImplementation 'com.epam.reportportal:agent-java-junit5:5.3.2'

**Additional context**

**Comment by HardNorth** [comment]
@siwonpawel It's technically impossible to find out if these separate process execution belong to one build or to several different builds, nothing inside java says about this, no environment variable or things like that, nothing. So it's user's area of responsibility to organise such projects into one launch. E.G. start one with a shell script and use this Launch UUID in subprojects with `rp.launch.uuid` property passing.

More properties described here: https://github.com/reportportal/client-java?tab=readme-ov-file#common-parameters
