### ISSUE TITLE
Final item in structure sequence?

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/agent-java-junit5#3]
@sbabcoc what is the final item type in sequence, according to implementation?
is it type `TEST` or `STEP`?

according to our logic, it should be `STEP`. Which is equal to Test Case itself.
And `TEST` type is equal to Test Class level.

Yes, i know, not so obvious. And it is a point for refactoring.
But this structure is supported by UI right now, properly representing items on UI.

cc @avarabyeu

**Comment by sbabcoc** [comment]
I thought I retained the original call structure, but the structure of the launches seems not to look like what you're expecting.
In the JUnit 4 agent, the actual test methods (Test, Before, After...) are reported as `STEP` items. They show up in the UI as "Test", "Before Method", etc.
In the JUnit 5 agent, these notations are missing in the UI, indicating that the items for the methods are probably being reported as `TEST`, or perhaps not being reported as anything in particular.

**Comment by DzmitryHumianiuk** [comment]
@sbabcoc can we update it somehow, for jUnit5, so it will send final test as `STEP`?
I know, it's wierd, but this we putted 5 years ago, with respect to BDD project.
And at the moment.

- Launch is launch
- Suite is `SUITE`
- Test Class is `TEST`
- TestCase is `STEP`

All the rest, like After..,Before.. are subtypes of `STEP`

We gonna update it, those types, after 5.0 release. But it will be painful.

**Comment by sbabcoc** [comment]
No objection from me. The proper item hierarchy isn't documented anywhere that I can find, and I apparently broke the hierarchy with my PR. It would be a good idea to beef up the documentation to include this detail.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova do we have this hierarchy documented somehow? 
see my comment https://github.com/reportportal/agent-java-junit5/issues/3#issuecomment-415582884

if yes, then we need to make it more visible and findable

**Comment by DzmitryHumianiuk** [comment]
@sbabcoc could you plz send a pull request with fix?

**Comment by evjlobanova** [comment]
@DzmitryHumianiuk you can find information about hierarchy here http://reportportal.io/docs/View-launches
![image](https://user-images.githubusercontent.com/30413511/44596901-84580100-a7d6-11e8-9b1f-0fc6cfcf9c8d.png)

**Comment by DzmitryHumianiuk** [comment]
I see.
we need to have it here http://reportportal.io/docs/Logging-Integration
and extent every agent repos, with relations matrix

**Comment by DzmitryHumianiuk** [comment]
@sbabcoc fixed. merged
