### ISSUE TITLE
Make Extensions Extendable

### ISSUE THREAD

**Issue by willyhalim** [reportportal/agent-java-junit5#32]
Can we make methods in the extensions extendable . Sometimes we want to group issue type when certain custom annotation happens / introduce new annotation called description.

Need an easy way to add custom behaviour by extending the Junit5Extension

**Comment by HardNorth** [comment]
@willyhalim What do you mean? I didn't find a class called `Junit5Extension`. Current `ReportPortalExtension` class implements JUnit's `Extension` interface which signals that the class is an extension and a bunch of other interfaces. All these methods are public and the class is public too. That means extendable.

**Comment by HardNorth** [comment]
Abadoned
