### ISSUE TITLE
Could reportPortalExtension class have more public access methods?

### ISSUE THREAD

**Issue by Ignnn** [reportportal/agent-java-junit5#71]
Hey, reportPortal team!

I would be grateful if most of reportPortalExtension  methods could be public access instead of private.

For example I would like to override reportSkippedClassTests method - as I understand it is left empty for that reason. To send some logs to rp5 launch it actually requires both to start/finish testItem. Those methods are actually prepared, but they are private and I cant reuse it directly. I have two options - to rewrite it from scratch, which is code consuming... or to invoke those method as workaround...

Other methods, that could also be set as public access - getExecutionStatus /sendStackTraceToRP ...

Thanks, guy!

**Comment by HardNorth** [comment]
Done. Please use:
https://bintray.com/epam/reportportal/agent-java-junit5/5.0.3
