### ISSUE TITLE
How to get results from multi module Maven project into one launch?

### ISSUE THREAD

**Issue by wlad** [reportportal/agent-java-junit5#73]
Hi, I'm trying ReportPortal in multi module project. Not sure if I'm doing things right but there are two issues I ran into:
1. It seems results from each module are send as separate launches
2. We are using Junit5 (org.junit.jupiter) to run unit tests which also includes old Junit4 tests. Results of Junit4 test are not displayed in ReportPortal

Now I wonder
1. Does ReportPortal support multi module maven projects? If so, how to set it up correctly?
2. Is it possible to display results of Junit4 tests executed with Junit5 (org.junit.vintage)?

**Comment by HardNorth** [comment]
Hello,
1. If you run them simultaneously, then yes. RP will join all launches on one machine by default. Otherwise you need to merge them manually or using merge API: `POST ​/v1​/{projectName}​/launch​/merge`
2. We didn't test such things as running one launch on different engines. Anyway you can try to use [JUnit 4](https://github.com/reportportal/agent-java-junit) agent. But it is still developing.

**Comment by wlad** [comment]
Thaks for reply. I'll check how to merge results.

In a multi module project where I'm supposed to place reportportal.properties, logback.xml etc.? As of now I have multiple of them in test/resources folder of each module.

**Comment by HardNorth** [comment]
@wlad, this question is related to Maven. RP agents will locate these files in classpath, so if you make maven to have a common folder which will be included into classpath, then you can put just one copy of each file here. Otherwise you should store multiple copies in resource folders.

**Comment by HardNorth** [comment]
Looks answered

**Comment by wlad** [comment]
not sure if thats the best way but adding `<resources>` to my parent pom's build section allows me to have all my RP configuration in one place in `application/src/test/resources`

```xml
<build>
        <resources>
            <resource>
                <directory>../application/src/test/resources</directory>
            </resource>
            <resource>
                <directory>../application/src/main/resources</directory>
            </resource>
            <resource>
                <directory>../base/src/main/resources</directory>
            </resource>
            <resource>
                <directory>../jooq-pq/src/main/java/org/ehrbase/jooq/binding</directory>
            </resource>
            <resource>
                <directory>../rest-ehr-scape/src/main/resources</directory>
            </resource>
            <resource>
                <directory>../rest-openehr/src/main/resources</directory>
            </resource>
            <resource>
                <directory>../service/src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
            ...

...
</build>
```
