### ISSUE TITLE
How to set the launch name in reportportal.properties from an EVN variable?

### ISSUE THREAD

**Issue by wlad** [reportportal/agent-java-junit5#74]
Let's assume I have the following reportportal.properties file

```
[reportportal.properties]
rp.endpoint = http://IP_ADRESS:8080
rp.uuid = 123...
rp.launch = ${REPORTPORTAL_LAUNCH_NAME}
rp.project = myproject
```

How to set rp.launch to the value of ENV var (environment variable) i.e. `${REPORTPORTAL_LAUNCH_NAME}`?

**Comment by wlad** [comment]
Not exactly the answer to the question I asked but actually exactly what I need 😄 

It's possible to overide the value from command line by passing `-Drp.launch=some-value` to `mvn` command. i.e. 
```
mvn package -Drp.launch=EHRBASE-BUILD-123

OR

mvn package -Drp.launch=${CIRCLE_BUILD_NUM}
```

**Comment by ntthaibk** [comment]
> Not exactly the answer to the question I asked but actually exactly what I need 😄
> 
> It's possible to overide the value from command line by passing `-Drp.launch=some-value` to `mvn` command. i.e.
> 
> ```
> mvn package -Drp.launch=EHRBASE-BUILD-123
> 
> OR
> 
> mvn package -Drp.launch=${CIRCLE_BUILD_NUM}
> ```

it's perfect, thank you, just wonder how they pass this from maven since I didn't see any config
