### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by wlad** [reportportal/agent-java-junit5#76]
http://reportportal.io/docs/JVM-based-clients-configuration   leads to nowhere

![image](https://user-images.githubusercontent.com/64201310/99241211-d5ac9a80-27fd-11eb-920a-3ff7a11ee1a3.png)

**Comment by HardNorth** [comment]
I don't see this page on our website anymore, so the issue looks obsolete

**Comment by wlad** [comment]
no, the issue (the dead link) is in the README --> https://github.com/reportportal/agent-java-junit5#step-5---link-reportportal-with-your-tests
