### ISSUE TITLE
RP creates separate launches for surefire and failsave results of one maven build

### ISSUE THREAD

**Issue by wlad** [reportportal/agent-java-junit5#77]
Now I have a single module project at hand. Still RP creates multiple launches during a single `mvn clean install`. It creates separate launches ~per test class~ for surefire and failsave results. Is this expected behavior?

Can it be configured to merge results of one build into a single launch? (without the need to use merge API endpint)

![image](https://user-images.githubusercontent.com/64201310/99245940-c11fd080-2804-11eb-88e2-8526d69680b1.png)

![image](https://user-images.githubusercontent.com/64201310/99245957-c846de80-2804-11eb-879d-4f8ef27ea4a5.png)

**Comment by wlad** [comment]
here is the relevant part from my pom.xml

```
<build>
        <plugins>
         ...
          <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
    ...
    </plugins>
</build>


<dependencies>
        ....
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring-boot.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.200</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-junit5</artifactId>
            <version>5.0.3</version>
        </dependency>
        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>5.0.3</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
    </dependencies>
```

**Comment by HardNorth** [comment]
Please provide an example project to reproduce.

**Comment by HardNorth** [comment]
And actually we are not a free test automation academy, I'm not supposed to answer on maven configuration questions.

**Comment by wlad** [comment]
> So please provide an example project to reproduce.

https://github.com/testautomation/examples-java/tree/master/example-junit5

**Comment by HardNorth** [comment]
I don't see any reason why we should provide an example on spring-boot. By that logic we need to provide examples on: guice, plain java, old-style spring, dagger, OSGI or whatever DI / application framework one found. We have integration instructions which I keep up-to-date: https://github.com/reportportal/agent-java-junit5/blob/develop/README.md
I believe it's more than enough.

Regarding to failsafe plugin I recall there was a feature is that this plugin start every test in a separate fork. Hence people get one launch per a class. To overcome it one need to set `forkCount` parameter into `1`. But in that case the necessity of the failsafe plugin is uncertain. And I believe not only our reporting tool have such issues with failsafe.
