### ISSUE TITLE
Performance issue(?) - launch of Junit5 examples takes about five minutes to finish

### ISSUE THREAD

**Issue by wlad** [reportportal/agent-java-junit5#78]
Executing this [example tests](https://github.com/reportportal/examples-java/tree/master/example-junit5) creates a launch which takes about 5 minutes to finish. The used Linux (Ubuntu 18.10) VPS has 4 CPU cores and 8 GB of RAM.

Is this normal?

**Comment by HardNorth** [comment]
I didn't implement they as performant, their goal to demonstrate features. The agent is used internally by our team and runs 2k+ of tests on daily basis without any significant resource consumption.
