### ISSUE TITLE
Broken badge's link to UserVoice in agent-java-junit5 README.md

### ISSUE THREAD

**Issue by Cliffart44** [reportportal/agent-java-junit5#79]
### [Here it is](https://github.com/reportportal/agent-java-junit5#--)
---
![Broken](https://user-images.githubusercontent.com/64852774/102387173-1c4e0a00-3fe1-11eb-8929-b720045ab065.png)
---
![UserVoice](https://user-images.githubusercontent.com/64852774/102387261-37207e80-3fe1-11eb-89a0-8875273fad72.png)

**Comment by HardNorth** [comment]
OK, removed, since we do not use uservoice anymore. Thank you!
