### ISSUE TITLE
Launch not created

### ISSUE THREAD

**Issue by roma-diadiura** [reportportal/agent-java-junit5#81]
Hi RP team,

we use reportportal more than 1 year. Our regression consists of 4 different java executions and after regression is finished we expect 4 launches to be present in RP. But sometimes (few times a week) we have only 3 launches, or even 2. In Jenkins job logs all is OK, all 4 java executions are finished successfully, no errors from RP either. But RP server API log is flooded with errors: 
1) 'Launch not found. Did you use correct Launch ID' (full version attached)
2) 'Test Item not found. Did you use correct Test Item ID'

At first glance it seems RP server consumed a 'createLaunch' request, but the Launch itself was not created and no errors returned either. We are facing this problem for a few last months

Expected: if the launch was not created we receive a corresponding error message, or null instead of UUID.

We run tests on Selenoid using parallelization (6 threads)
RP 5.3.4       
        <dependency>
                <groupId>com.github.reportportal</groupId>
                <artifactId>agent-java-junit5</artifactId>
                <version>5.0.3</version>
            </dependency>
            <dependency>
                <groupId>com.github.reportportal</groupId>
                <artifactId>logger-java-logback</artifactId>
                <version>5.0.3</version>
            </dependency>
            <dependency>
                <groupId>com.github.reportportal</groupId>
                <artifactId>client-java</artifactId>
                <version>5.0.18</version>
            </dependency>
            
        
[RpExceptions.txt](https://github.com/reportportal/reportportal/files/5816743/RpExceptions.txt)

**Comment by HardNorth** [comment]
More likely it is JUnit 5 agent specific. Will se what I can do.

**Comment by HardNorth** [comment]
@roma-diadiura Hey, try this version: https://github.com/reportportal/agent-java-junit5/releases/tag/5.0.4

**Comment by HardNorth** [comment]
@roma-diadiura Any updates?

**Comment by roma-diadiura** [comment]
@HardNorth 
Hi, I've updated agent-java-junit5 to version 5.0.4 in Feb-11.
It didn't help, incomplete regressions occur regularly :(

**Comment by HardNorth** [comment]
@roma-diadiura, sorry, but I'm out of ideas. We use this agent in our internal testing and do not observe such behavior. Moreover this is not client-specific, because thousands of users use the client every day. So please provide any agent logs/examples to move forward.

**Comment by roma-diadiura** [comment]
@HardNorth , I've sent required logs to you in slack

**Comment by HardNorth** [comment]
Cannot reproduce / no other complains
